# Generated by Django 5.0.1 on 2024-06-23 17:14

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.UUID('cf9ba4be-abd4-47c5-884d-cffb2838ecea'), max_length=225)),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blink.customersupport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blink.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sender', models.CharField(max_length=225)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_room.room')),
            ],
        ),
    ]
