name: blink
description: An online market shopping project for software engineer course - SBU CE
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.7
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.8
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: shabnam
      fonts:
        - asset: assets\fonts\Shabnam.ttf
  assets:
    - images/bell.png
    - images/question.png
    - images/seller.png
    - images/motorbike.png
    - images/people.png
    - images/user.png
    - images/key.png
    - images/logo.png
    - images/notification.png
    - images/user2.png
    - images/home.png
    - images/cart.png
    - images/account.png
    - images/plus.png
    - images/remove.png
    - images/img.png
    - images/trash.png
    - images/pencil.png
    - images/blink.png
    - images/chat_background.png
    - images/send-message.png
    - images/search.png
    - images/options.png
    - images/pizza.png
    - images/arayeshi.png
    - images/digital.png
    - images/market.png
    - images/lebas.png
    - images/product.png
    - images/shop.png
    - images/location.png
    - images/addimage.png
    - images/boxing.png
    - images/packing.png
    - images/delivery.png
    - images/deliverd.png
    - images/copy.png
    - images/star.png
    - images/star_empty.png
    - images/commentratesent.png
    - images/graph.png
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/logo.png"
    background_color: "#FFFFFF"
#    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/logo.png"
